### ISSUE TITLE
Manual Game Time on Browser/Desktop/OBS versions? 

### ISSUE THREAD

**Issue by jB0ne90** [LiveSplit/LiveSplitOne#678] opened 2022-02-21 22:49 UTC
Hello!

M1 user here! Is there currently a way of doing Manual Game Time in either the Browser, Desktop or OBS version of One? 

If so, any pointers? 😅

Keep up the great work!

**Comment by DarkRTA** [comment] 2022-12-14 01:52
this is a duplicate of #364

**Comment by CryZe** [comment] 2024-05-11 13:05
I'm working on Manual Game Time support now, should be available very soon. However I'll close this as a duplicate, the work is tracked in the issue mentioned by Dark.

**Closed by CryZe** 2024-05-11 13:05 UTC
