### ISSUE TITLE
Does Livesplit One support auto splitting?

### ISSUE THREAD

**Issue by DarkJarris** [LiveSplit/LiveSplitOne#126] opened 2018-11-23 16:06 UTC
I'm looking for something that is cross platform and supports autosplitting. As Livesplit supports it, does LiveSplit One?

**Comment by hallcristobal** [comment] 2018-11-23 16:32
Auto-splitting in LiveSplit One is currently in research and development stages, it is not yet a fully fleshed out feature like in current LiveSplit.

**Comment by bryanwillis7** [comment] 2019-01-26 20:01
Best of luck. I'd really like to speedrun Nier Automata on linux, and currently the use of an autosplitter is what's holding me back, as linux has no options for this and the community requires one for removal of load times. I hope you guys are able to make progress on this.

**Comment by CryZe** [comment] 2019-01-26 20:06
We already have working auto splitters for A Hat in Time and Celeste that can be written in either C, C++, Rust or JavaScript / TypeScript (and theoretically you can use even more languages). So we are making good progress on this.

**Comment by wooferzfg** [comment] 2019-10-28 02:06
duplicate of https://github.com/LiveSplit/LiveSplitOne/issues/176

**Closed by wooferzfg** 2019-10-28 02:06 UTC
Labels: duplicate
